baseURL = "https://flipt.io/"
languageCode = "en-us"
title = "Flipt"
theme = "book"

# (Optional) Set this to true to enable 'Last Modified by' date and git author
#  information on 'doc' type pages.
# enableGitInfo = true

# (Optional) Theme is intended for documentation use, therefore it doesn't render taxonomy.
# You can remove related files with config below
disableKinds = ['taxonomy', 'taxonomyTerm']

[params]
  BookLogo = '/img/logo.svg'
  BookMenuBundle = '/menu'
  BookToC = 1
