googleAnalytics = "UA-44979762-7"
baseURL = "https://flipt.io/"
languageCode = "en-us"
title = "Flipt"
theme = "book"
enableGitInfo = true

# (Optional) Theme is intended for documentation use, therefore it doesn't render taxonomy.
# You can remove related files with config below
disableKinds = ['taxonomy', 'taxonomyTerm']

[params]
  BookLogo = '/img/logo.svg'
  BookMenuBundle = '/menu'
  BookToC = 1
  BookRepo = "https://github.com/markphelps/flipt.io"
